plugins {
    id "com.android.application"
    id "kotlinx-serialization"
    id "com.android.legacy-kapt"
    id "dagger.hilt.android.plugin"
}

apply from: "$rootDir/detekt.gradle"

android {
    compileSdk buildConfig.compileSdk

    defaultConfig {
        applicationId "com.infinum.jsonapix.sample"
        minSdk buildConfig.minSdk
        targetSdk buildConfig.targetSdk
        versionCode 1
        versionName releaseConfig.version
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()
            testLogging {
                events("PASSED", "FAILED", "SKIPPED")
            }
        }
    }
    namespace 'com.infinum.jsonapix'
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}

dependencies {
    // Comment this out for testing local deploy
    implementation project(":core")
    kapt project(":processor")
    implementation project(":retrofit")
    lintChecks project(path: ':lint')

    // Uncomment this for testing local deploy
//    implementation packages.jsonapix.core
//    kapt packages.jsonapix.processor
//    implementation packages.jsonapix.retrofit
//    lintChecks packages.jsonapix.lint

    implementation packages.retromock.core
    implementation packages.retrofit.core
    implementation packages.kotlin.core
    implementation packages.kotlin.serialization_core
    implementation packages.androidx.core
    implementation packages.androidx.appcompat
    implementation packages.hilt.core
    implementation packages.lifecycle.runtime
    implementation packages.lifecycle.common
    implementation packages.lifecycle.viewmodel
    implementation packages.activity.core
    implementation packages.fragment.core
    kapt packages.hilt.compiler
    implementation packages.material

    testImplementation packages.junit.api
    testRuntimeOnly packages.junit.engine
    testRuntimeOnly packages.junit.platform_launcher
    testImplementation packages.junit.params
}